version: "3.7"

services:
  db:
    image: postgres:12.1
    volumes:
      - ./src/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  web:
    build: .
    command: resto-server
    volumes:
      - .:/code
      - ./config/resto.example.ini:/etc/peopledoc-test/resto.ini
    ports:
      - 8080:8080
    depends_on:
      - db
